/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import business.EcoSystem;
import business.Enterprise.BloodBankEnterprise;
import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author PARAKH MAHAJAN
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private EcoSystem business;
    private Enterprise enterprise;
    /**
     * Creates new form AdminWorkAreaJPanel
     */

    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        this.enterprise =  enterprise;
        valueJLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseJLabel = new javax.swing.JLabel();
        valueJLabel = new javax.swing.JLabel();
        BtnManageOrganization = new javax.swing.JButton();
        BtnManageEmployee = new javax.swing.JButton();
        BtnManageDonor = new javax.swing.JButton();
        BtnManageUser = new javax.swing.JButton();
        dataButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 33, 284, 31));

        enterpriseJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        enterpriseJLabel.setText("Enterprise :");
        add(enterpriseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 109, 120, 30));

        valueJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        valueJLabel.setText("<Value>");
        add(valueJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 109, 120, 30));

        BtnManageOrganization.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnManageOrganization.setText("Manage Organization");
        BtnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageOrganizationActionPerformed(evt);
            }
        });
        add(BtnManageOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 204, -1, -1));

        BtnManageEmployee.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnManageEmployee.setText("Manage Employee");
        BtnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageEmployeeActionPerformed(evt);
            }
        });
        add(BtnManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 283, 195, -1));

        BtnManageDonor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnManageDonor.setText("Manage Donor");
        BtnManageDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageDonorActionPerformed(evt);
            }
        });
        add(BtnManageDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 364, 195, -1));

        BtnManageUser.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnManageUser.setText("Manage User");
        BtnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageUserActionPerformed(evt);
            }
        });
        add(BtnManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 443, 195, -1));

        dataButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        dataButton.setText("Data analysis");
        dataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataButtonActionPerformed(evt);
            }
        });
        add(dataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageOrganizationActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnManageOrganizationActionPerformed

    private void BtnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageEmployeeActionPerformed
        // TODO add your handling code here:
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnManageEmployeeActionPerformed

    private void BtnManageDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageDonorActionPerformed
        // TODO add your handling code here:
        ManageDonorJPanel manageDonorJPanel = new ManageDonorJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageDonorJPanel", manageDonorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnManageDonorActionPerformed

    private void BtnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageUserActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", manageUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnManageUserActionPerformed

    private void dataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataButtonActionPerformed
        // TODO add your handling code here:
        DataAnalysisJPanel dataAnalysisJPanel = new DataAnalysisJPanel(userProcessContainer, enterprise, organization, business);
        userProcessContainer.add("DataAnalysisJPanel", dataAnalysisJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_dataButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnManageDonor;
    private javax.swing.JButton BtnManageEmployee;
    private javax.swing.JButton BtnManageOrganization;
    private javax.swing.JButton BtnManageUser;
    private javax.swing.JButton dataButton;
    private javax.swing.JLabel enterpriseJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel valueJLabel;
    // End of variables declaration//GEN-END:variables
}
