/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import business.Organization.DonorOrganization;
import business.Organization.Organization;
import business.Organization.OrganizationDirectory;
import business.Person.Employee;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PARAKH MAHAJAN
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private OrganizationDirectory organizationDirectory;

    /**
     * Creates new form ManageEmployeeJPanel
     */
    ManageEmployeeJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        populateOrganizationTypeComboBox();
        populateEmployeeTypeComboBox();
    }

    public void populateOrganizationTypeComboBox() {
        organizationTypeComboBox.removeAllItems();
        for (Organization organization : organizationDirectory.getOrganizationList()) {
            if (organization instanceof DonorOrganization) {

            } else {
                organizationTypeComboBox.addItem(organization);
            }
        }
    }

    public void populateEmployeeTypeComboBox() {
        employeeTypeComboBox1.removeAllItems();
        for (Organization organization : organizationDirectory.getOrganizationList()) {
            if (organization instanceof DonorOrganization) {

            } else {
                employeeTypeComboBox1.addItem(organization);
            }
        }
    }

    public void populateTable(Organization organization) {
        DefaultTableModel model = (DefaultTableModel) manageEmployeeTable.getModel();
        model.setRowCount(0);

        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
            Object[] row = new Object[2];
            row[0] = employee.getEmployeeId();
            row[1] = employee.getFirstName();
            model.addRow(row);
        }

    }

    public boolean validation() {
        if (firstNameTextField.getText().equals("") || lastNameTextField.getText().equals("") || emailTextField.getText().equals("") || ageTextField.getText().equals("")
                || contactTextField.getText().equals("") || addressTextArea.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "All fields are mandatory");
            return false;
        } else {
            String namePattern = "[a-zA-Z]+\\.?";
            String name = firstNameTextField.getText();

            if (!(name.matches(namePattern))) {

                JOptionPane.showMessageDialog(null, "Please enter a valid first name");
                return false;
            }

            String namePattern2 = "[a-zA-Z]+\\.?";
            String lastName = lastNameTextField.getText();

            if (!(lastName.matches(namePattern2))) {

                JOptionPane.showMessageDialog(null, "Please enter a valid last name");
                return false;
            }

            String emailPattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
            String email = emailTextField.getText();

            if (!(email.matches(emailPattern))) {

                JOptionPane.showMessageDialog(null, "Please enter a valid email ID ");
                return false;
            }

        }

        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageEmployeeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        organizationTypeComboBox = new javax.swing.JComboBox();
        employeeTypeComboBox1 = new javax.swing.JComboBox();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        BtnAddEmployee = new javax.swing.JButton();
        BtnRemoveEmployee = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Employee");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 290, 28));

        manageEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageEmployeeTable);
        if (manageEmployeeTable.getColumnModel().getColumnCount() > 0) {
            manageEmployeeTable.getColumnModel().getColumn(0).setResizable(false);
            manageEmployeeTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 730, 100));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Organization :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Organization :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 120, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("First Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 100, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Last Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 100, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Email Id :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 100, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Age :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Contact Number :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 140, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Address :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 110, -1));

        organizationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationTypeComboBoxActionPerformed(evt);
            }
        });
        add(organizationTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        employeeTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(employeeTypeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 315, -1));
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 315, -1));
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 315, -1));

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 315, -1));
        add(contactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 330, -1));

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane2.setViewportView(addressTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 330, 46));

        BtnAddEmployee.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnAddEmployee.setText("Add Employee");
        BtnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddEmployeeActionPerformed(evt);
            }
        });
        add(BtnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, 170, -1));

        BtnRemoveEmployee.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnRemoveEmployee.setText("Remove Employee");
        BtnRemoveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveEmployeeActionPerformed(evt);
            }
        });
        add(BtnRemoveEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 680, -1, -1));

        BtnBack.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BtnBack.setText("<< Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 125, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Gender :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 100, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddEmployeeActionPerformed
        // TODO add your handling code here:
        if (validation()) {
            try {

                Organization organization = (Organization) employeeTypeComboBox1.getSelectedItem();
                Employee employee = organization.getEmployeeDirectory().addEmployee();
                employee.setFirstName(firstNameTextField.getText());
                employee.setLastName(lastNameTextField.getText());
                employee.setEmailId(emailTextField.getText());
                employee.setAge(Integer.parseInt(ageTextField.getText()));
                employee.setPhoneNumber(contactTextField.getText());
                employee.setAddress(addressTextArea.getText());
                employee.setGender((String) genderComboBox.getSelectedItem());
                JOptionPane.showMessageDialog(this, "Employee is added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

                firstNameTextField.setText("");
                lastNameTextField.setText("");
                emailTextField.setText("");
                ageTextField.setText("");
                contactTextField.setText("");
                addressTextArea.setText("");
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Please enter appropriate values in age field");
            }
        }
    }//GEN-LAST:event_BtnAddEmployeeActionPerformed

    private void BtnRemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveEmployeeActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageEmployeeTable.getSelectedRow();
        try {
            if (selectedRow >= 0) {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "Would you like to delete employee detail", "Warning", dialogButton);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    //Employee employee = (Employee) manageEmployeeTable.getValueAt(selectedRow, 0);
                    for (Organization organization : organizationDirectory.getOrganizationList()) {
                        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
                            organization.getEmployeeDirectory().removeEmployee(employee);
                            populateTable(organization);
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BtnRemoveEmployeeActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void organizationTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationTypeComboBoxActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) organizationTypeComboBox.getSelectedItem();
        if (organization != null) {
            populateTable(organization);
        }
    }//GEN-LAST:event_organizationTypeComboBoxActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ageTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddEmployee;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnRemoveEmployee;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JComboBox employeeTypeComboBox1;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTable manageEmployeeTable;
    private javax.swing.JComboBox organizationTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
